name: client
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: aemino <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http: ^0.12.0+1

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
  style_genshu:
    git: git://github.com/aemino/dart-style-genshu
